### ISSUE TITLE
Kiwi Egg Crate & Kiwi Fruit Crate

### ISSUE THREAD

**Issue by SimulationOfMario** [axperty/cratedelight#4]
I think it's a good idea that you can add a crate for the kiwi eggs from the Jagm's Kiwis mod.

Since you have a crate of chicken eggs, I think it makes sense.

The mod also has the kiwi fruit, you can make another crate for it.

Hopefully for version 1.20.1, please!

I really like your mod! :)

**Comment by axperty** [comment]
Hi SimulationOfMario,

I forgot to respond to this message, I want to apologize, I added your idea to Crate Delight, and the **Kiwi Egg Crate will be** on the next update! I will respond to this conversation again to let you know when the update is out.

Have a good day,
Axperty.

**Comment by axperty** [comment]
Hi SimulationOfMario,

Crate Delight has been updated and it now includes the **Kiwi Egg Crate** and the **Kiwifruit Crate.**

Thank you so much for your suggestion!

[Download on CurseForge](https://www.curseforge.com/minecraft/mc-mods/crate-delight-forge) | [Download on Modrinth](https://modrinth.com/mod/crate-delight)

Have a great day,
Axperty.
