### ISSUE TITLE
BetterEnd crates in the Forge version

### ISSUE THREAD

**Issue by SimulationOfMario** [axperty/cratedelight#5]
Hey! it's me, again

I have doubts about what it really is like, but I play in Forge but using Sinytra Connector to be able to play with mods like BetterEnd.

I have noticed that this affects the fact that, since I use Forge's Crate Delight, it seems that you have not implemented the BetterEnd crates for the Forge version because BetterEnd is fabric-only.

Now that Sinytra exists, I think you should add those crates, because I THINK I can't just use the Crate Delight version for fabric because I think that if you use a forge mod (Farmer's Delight), its addons must be from forge as well (I imagine that It is due to the difference in libraries between Forge and Fabric that Sinytra can no longer handle at that level), I have already verified this with the Brewin' And Chewin' addon, which is only for fabric and I cannot use it, but I don't know if it will happen with your addon, I also think it is better that you simply add the BetterEnd crates to the Forge version (and I hope that works with that...)

**Comment by axperty** [comment]
Hi SimulationOfMario,

I'll see what I can do, I think it should be possible to implement the crates from BetterEnd in the Forge version of Crate Delight. I'm currently working on an update, and it will be released soon.

Have a good day,
Axperty.

**Comment by axperty** [comment]
Hi SimulationOfMario,

Small update, even though Crate Delight was updated today, this idea is still being considered, and I'm currently testing if everything works correctly so I can add the integration with BetterEnd.

Have a good day,
Axperty.

**Comment by SimulationOfMario** [comment]
That's great! 

I'm still not sure about the compatibility of a Forge addon interacting well with a Fabric mod, but I hope it works... 

Forge's REI supports and displays BetterEnd ritual recipes (I switched from JEI to REI because of that), would it serve as support that mods of different launchers/libraries work well?

**Comment by SimulationOfMario** [comment]
Hi @axperty 

How is going on with this feature? Any chance of having BetterEnd crates in the forge version?

**Comment by axperty** [comment]
Hi,

I'm currently working on this, I'll let you know when the update is out.

**Comment by axperty** [comment]
Hi @SimulationOfMario,

After some coding, I was able to add the crate and bag from the BetterEnd mod, I'll try to do the same in the Neoforge version:

![image](https://github.com/user-attachments/assets/ed6d9d08-cec5-43a2-9d04-94a6da2a7cc2)

**Comment by SimulationOfMario** [comment]
Hi @axperty!

That's so cool! 
How many crates are? Is there a cubozoa gelatine crate? 
Idk, but having that two is great!

**Comment by axperty** [comment]
Those are the End Fish Crate and Ender Dust Bag, for now, those are the only ones that are in Crate Delight. I'll release this update in the next few hours.

**Comment by SimulationOfMario** [comment]
Btw, I'm making a modpack and your mod is on the list!

**Comment by axperty** [comment]
Amazing! Can't wait to try it, let me know the name of the modpack.

**Comment by SimulationOfMario** [comment]
I call it Minecraft Definitive Edition, but I still don't publish it.

I'm making its description because it's too long and also I'm configuring some mods configs!

I hope I can publish it on this month!
I will tell you!
